Allow Disabling Rediscovery
pywemo/pywemo pull request #127
Opened 2019-01-04 00:28 UTC by sqldiablo

## Description:
This change allows a user to disable pywemo's rediscovery feature. This will be used by a future change to Home Assistant so that Home Assistant can use its own rediscovery logic.

## BREAKING CHANGE:
If calling a device action (such as to get the state, set the state, etc. fails, it will now raise an ActionException that will be returned to the caller (even outside of pywemo). This was needed so that Home Assistant can catch the error and know that a device action\update has failed.

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] There is no commented out code in this PR.

2019-01-04 10:16 UTC, pavoni requested changes
Looks good to me. 

One suggestion, and one question.

BTW now you have access to the repo - you can just branch there - rather than needing a local repo.

Seemed to work OK with my Makers.

2019-01-04 10:16 UTC, pavoni commented on pywemo/ouimeaux_device/api/service.py
> +# The formatting here is a very hacky way around a too-long line flake8 error
I think it's possible to turn off flake checking for this http://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html

I think the previous code is clearer (and from your comment I think you agree!).

2019-01-04 10:16 UTC, pavoni commented on pywemo/ouimeaux_device/bridge.py
> +        if force_update or self.Lights is None or self.Groups is None:
Why did you want to add `force_update` as part of this PR?

2019-01-04 10:41 UTC, sqldiablo commented on pywemo/ouimeaux_device/bridge.py
> +        if force_update or self.Lights is None or self.Groups is None:
I was bringing the bridge in-line with the other devices for this. I can default it to True, to make backwards compatibility a little safer.

2019-01-04 10:43 UTC, sqldiablo commented on pywemo/ouimeaux_device/api/service.py
> +# The formatting here is a very hacky way around a too-long line flake8 error
Yeah, this was a pain to deal with. You usually use an inline "# noqa" comment to ignore stuff like this, but being a multi-line string, that didn't work. I'll keep checking to see if I missed the way to do it.

2019-01-04 10:46 UTC, sqldiablo commented
As for branching in this repo, I'd feel a little "safer" if I work in my fork and merge back into here, unless you object. I didn't want to muddy things up in this repo too much or cause an issue I can't cleanly fix. At least with my fork, I can always delete and recreate it if things get too out of hand.

2019-01-04 10:48 UTC, pavoni commented
Completely your choice - but I always found keeping a fork in step to be a pain.

2019-01-04 10:52 UTC, sqldiablo commented
Now that I actually know how (rebase wasn't my friend for a while), I've created a couple scripts that help me keep current, so it's not too bad.

2019-01-04 11:03 UTC, sqldiablo commented on pywemo/ouimeaux_device/api/service.py
> +# The formatting here is a very hacky way around a too-long line flake8 error
Yeah, this is a known bug in flake8 (https://gitlab.com/pycqa/flake8/issues/375). I can ignore the long-line error in the entire file and then revert this back to how it was.

2019-01-04 11:13 UTC, pavoni approved these changes

2019-01-04 11:14 UTC, sqldiablo commented on pywemo/ouimeaux_device/bridge.py
> +        if force_update or self.Lights is None or self.Groups is None:
I went ahead and defaulted it to True so it will behave the same if the parameter is omitted as it did before this change.

2019-01-04 11:26 UTC, merged

2019-01-11 22:48 UTC, sqldiablo commented
Linking this to #125, which this PR was a replacement for.