Fix compatability with Sylvania tunable white bulbs
pywemo/pywemo pull request #71
Opened 2017-03-31 00:09 UTC by emunsing

It seems that Osram/Sylvania Lightify tunable white bulbs report their status as float strings, which led to a typecasting issue when casting directly to int. This has now been tested to work with the Sylvania Lightify A19 Tunable White 60W equivalent bulb.

2017-04-02 09:08 UTC, pavoni requested changes
Thanks - looks good - couple of minor suggestions, then happy to merge and release. 

Assuming you're using this with HA - would you like to do the PR - or should I?

2017-04-02 09:08 UTC, pavoni commented on pywemo/ouimeaux_device/bridge.py
> +                value = tuple(int(float(v)) for v in value.split(':'))
Probably best to do `int(round(float(v)))`  which will round rather than truncate - and work on Python 2 & 3.

2017-04-02 09:08 UTC, pavoni commented on pywemo/ouimeaux_device/bridge.py
>                  value = int(value)
Could you also do `int(round(float(v))) `. Probably not needed for your devices - but could help with some other device!

2017-04-04 01:17 UTC, emunsing commented
Great, good catch- I like the update, and have pushed a new commit that addresses this. Let me know if there's anything else you catch! I'm new to pull requests, so let me know what's needed to wrap this up :)

2017-04-04 08:58 UTC, pavoni commented on pywemo/ouimeaux_device/bridge.py
>                  value = int(value)
@emunsing Don't know if you saw this - could you add the same code in line 110?

2017-04-04 08:59 UTC, pavoni commented
@emunsing One small suggestion that I think you missed (doing the same cast in the `else`).

Then I'll to merge and release. Thanks for the contribution.

2017-04-04 15:19 UTC, emunsing commented
Great, thanks for the catch- updated!

2017-04-04 15:39 UTC, pavoni approved these changes

2017-04-04 15:39 UTC, merged

2017-04-04 15:41 UTC, pavoni commented
Released as 0.4.16. Thanks.

Would you like to do the HA pull request - or shalI?

2017-04-04 17:32 UTC, emunsing commented
I'm not actually working with the the Home Assistant system, if that's what you're referring to by HA- go ahead and do the pull request!